import React from 'react';
import { StyleSheet, View } from 'react-native';
import { ThemedText } from './themed-text';
import { ThemedView } from './themed-view';
import { SimulationRecord } from '@/constants/mockData';
import { calculateEquityScore, getEquityLabel } from './EquityIndex';

export interface ReportCardProps {
  simulation: SimulationRecord | null;
}

export function ReportCard({ simulation }: ReportCardProps) {
  if (!simulation) return null;

  const score = calculateEquityScore(
    simulation.stakeholders || [],
    simulation.conflicts || [],
    simulation.blindSpots || []
  );

  const blindSpotsCount = simulation.blindSpots?.length || 0;
  const label = getEquityLabel(score, blindSpotsCount);

  const getColor = (val: number) => {
    if (val >= 80) return '#4CD964'; // Green
    if (val >= 50) return '#FFCC00'; // Amber
    return '#FF3B30'; // Red
  };

  const riskColor = getColor(score);

  return (
    <View style={styles.hiddenWrapper}>
      {/* This ID is targeted by html2canvas */}
      <View nativeID="report-card-export" style={styles.cardContainer}>
        
        {/* Header */}
        <View style={styles.header}>
          <ThemedText style={styles.brandTitle}>
            <ThemedText style={styles.brandDot}>🔵</ThemedText> ECHO
          </ThemedText>
          <ThemedText style={styles.brandSubtitle}>Decision Blind Spot Detector</ThemedText>
        </View>

        <View style={styles.divider} />

        {/* Policy Section */}
        <View style={styles.section}>
          <ThemedText style={styles.sectionLabel}>POLICY ANALYZED</ThemedText>
          <ThemedText style={styles.policyTitle}>"{simulation.decisionTitle}"</ThemedText>
        </View>

        <View style={styles.divider} />

        {/* Equity Index */}
        <View style={styles.section}>
          <ThemedText style={styles.sectionLabel}>EQUITY INDEX</ThemedText>
          <View style={styles.scoreRow}>
            <View style={styles.barBackground}>
              <View style={[styles.barFill, { width: `${score}%`, backgroundColor: riskColor }]} />
            </View>
            <ThemedText style={[styles.scoreValue, { color: riskColor }]}>{score} / 100</ThemedText>
          </View>
          <ThemedText style={[styles.riskLabel, { color: riskColor }]}>{label}</ThemedText>
        </View>

        <View style={styles.divider} />

        {/* Blind Spots */}
        <View style={styles.section}>
          <ThemedText style={styles.sectionLabel}>BLIND SPOTS DETECTED: {blindSpotsCount}</ThemedText>
          {simulation.blindSpots && simulation.blindSpots.length > 0 ? (
            <View style={styles.list}>
              {simulation.blindSpots.map((bs, idx) => (
                <ThemedText key={idx} style={styles.listItem}>🔴 {bs}</ThemedText>
              ))}
            </View>
          ) : (
            <ThemedText style={styles.listItem}>No significant blind spots detected.</ThemedText>
          )}
        </View>

        <View style={styles.divider} />

        {/* Stats */}
        <View style={styles.section}>
          <ThemedText style={styles.sectionLabel}>CONFLICTS DETECTED: {simulation.conflicts?.length || 0}</ThemedText>
          <ThemedText style={styles.sectionLabel}>STAKEHOLDERS ANALYZED: {simulation.stakeholders?.length || 0}</ThemedText>
        </View>

        <View style={styles.divider} />

        {/* Footer */}
        <View style={styles.footer}>
          <ThemedText style={styles.footerText}>
            Analyzed on {new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
          </ThemedText>
          <ThemedText style={styles.footerText}>echo-app.vercel.app</ThemedText>
          <ThemedText style={[styles.footerText, { marginTop: 16, opacity: 0.6 }]}>
            Generated by Echo — Decision Blind Spot Detector
          </ThemedText>
        </View>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  hiddenWrapper: {
    // Hide from normal view, but keep mounted so it can be captured
    position: 'absolute',
    top: -9999,
    left: -9999,
    opacity: 0,
    pointerEvents: 'none',
  },
  cardContainer: {
    width: 600,
    backgroundColor: '#0A0A0F',
    padding: 40,
    borderWidth: 1,
    borderColor: '#2A2A3A',
    borderRadius: 16,
  },
  header: {
    marginBottom: 24,
  },
  brandTitle: {
    fontSize: 28,
    fontWeight: '900',
    color: '#E8E8F0',
    letterSpacing: 1,
  },
  brandDot: {
    fontSize: 24,
    color: '#6E56FF', // Purple/blue accent approximation for emoji replacement if needed
  },
  brandSubtitle: {
    fontSize: 16,
    color: '#8B8B9E',
    marginTop: 4,
    fontWeight: '500',
  },
  divider: {
    height: 1,
    backgroundColor: '#2A2A3A',
    marginVertical: 24,
  },
  section: {
    gap: 8,
  },
  sectionLabel: {
    fontSize: 14,
    fontWeight: '800',
    color: '#8B8B9E',
    letterSpacing: 1.5,
  },
  policyTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#FFFFFF',
    lineHeight: 32,
  },
  scoreRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    marginTop: 8,
  },
  barBackground: {
    flex: 1,
    height: 16,
    backgroundColor: '#1A1A24',
    borderRadius: 8,
    overflow: 'hidden',
  },
  barFill: {
    height: '100%',
    borderRadius: 8,
  },
  scoreValue: {
    fontSize: 24,
    fontWeight: '900',
    width: 100,
  },
  riskLabel: {
    fontSize: 16,
    fontWeight: '700',
    marginTop: 8,
  },
  list: {
    marginTop: 8,
    gap: 12,
  },
  listItem: {
    fontSize: 18,
    color: '#E8E8F0',
    fontWeight: '500',
  },
  footer: {
    marginTop: 8,
  },
  footerText: {
    fontSize: 14,
    color: '#8B8B9E',
    lineHeight: 24,
  },
});
